# Generated by Django 5.0.3 on 2024-03-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rer_by',
            new_name='ref_by',
        ),
    ]
