# Generated by Django 4.2.7 on 2024-03-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_rer_by_profile_ref_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
